
[env]
TERM = "xterm-256color"

[window]
# title = "Alacritty"
padding.x = 10
padding.y = 10
dimensions = {columns = 130, lines = 40}
# startup_mode = "Maximized"
# startup_mode = "SimpleFullscreen"
decorations = "Buttonless"
# decorations = "Full"


opacity = 0.99
blur = false

[font]
#normal.family = "MesloLGS Nerd Font"
size = 15 

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[cursor]
style = "Beam"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
